services:

  dewshare-db:
    image: postgres:16
    restart: always
    env_file:
      - secrets.var
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dew -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  app:
    build: .
    image: dew-share
    restart: always
    env_file:
      - secrets.var
    depends_on:
      dewshare-db:
        condition: service_healthy

    ports:
      - "127.0.0.1:8117:80"
    volumes:
      - ./static:/app/static
    networks:
      - internal

volumes:
  db-data:

networks:
  internal:
